### ISSUE TITLE
ERROR 404

### ISSUE THREAD

**Issue by Praisecodes** [cyperblt/flora#1]
Hi there, I tried clicking on the GitHub pages in the lower right corner of my screen and when I got to the point where I see the page, it's show ERROR 404.
Why is that?
![issue](https://user-images.githubusercontent.com/73062242/148219801-73773d58-1971-4f44-9059-ca30854ed8dc.png)

**Comment by cyperblt** [comment]
It means it wasn't **Published**

**Comment by Praisecodes** [comment]
> It means it wasn't **Published**.
> 
> Though you can check it out [here](https://flora-redesigned.netlify.app/)

Totally amazing 
I love it
